---
- name: Generate VRFs config
  connection: network_cli
  hosts: all
 
  tasks:
    - name: Validate vrfs yaml file exits
      stat:
        path: "configs/vrfs/{{ inventory_hostname }}.yaml"
      register: vrfs_yaml
    - include_vars:
        file: "configs/vrfs/{{ inventory_hostname }}.yaml"
      when: vrfs_yaml.stat.exists == True

#    - name: Generate Vrf config
#      template:
#        src: "templates/vrfs.j2"
#        dest: "config_files/{{ inventory_hostname }}.config"
#      when: vrfs is defined

    - name: Push VRF config
      cisco.ios.ios_vrf:
        name: "{{ item.name }}"
        rd: "{{ item.rd }}"
      with_items: "{{ vrfs }}"
      when: vrfs is defined


...
