---
- name: Generate NTP config for Core
  connection: network_cli
  hosts: cores

  tasks:
    - include_vars:
        file: configs/ntp/core.yaml
    - name: Push VRF config to core switches
      ios_ntp:
        server: "{{ item.server }}"
        vrf: "{{ item.vrf }}"
        source_int: Loopback0
      with_items: "{{ ntps }}"
      when: ntps is defined


- name: Generate NTP config for all devices
  connection: network_cli
  hosts: dist,routers
  
  tasks:
    - include_vars:
        file: configs/ntp/global.yaml
    - name: Push VRF config to remaining devices
      ios_ntp:
        server: "{{ item.server }}"
        vrf: "{{ item.vrf }}"
        source_int: Loopback0
      with_items: "{{ ntps }}"
      when: ntps is defined

...