---
vlans:
  - vid: 132
    name: s3-core-dist-mgmt
    interface:
      description: "s3 core to dist mgmt vrf"
      vrf: mgmt
      ip: 
        address: 172.16.1.18/30 

  - vid: 999
    name: Native


...
