---
vlans:
  - vid: 124
    name: s2-s4-mgmt
    interface:
      description: "s2-s4 core mgmt vrf"
      vrf: mgmt
      ip:
        address: 172.16.1.10/30 
  
  - vid: 134
    name: s3-s4-mgmt
    interface:
      description: "s3-s4 core mgmt vrf"
      vrf: mgmt
      ip: 
        address: 172.16.1.14/30
  
  - vid: 142
    name: s4-core-dist-mgmt
    interface:
      description: "s4 core to dist mgmt vrf"
      vrf: mgmt
      ip: 
        address: 172.16.1.21/30 

  - vid: 999
    name: Native


...

